{{- if and .Values.vault.enabled (not .Values.vault.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "air-gateway.fullname" . }}-vault
  labels:
    {{- include "air-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  VAULT_ACCESS_KEY: {{ .Values.vault.accessKey | quote }}
  VAULT_SECRET_KEY: {{ .Values.vault.secretKey | quote }}
{{- end }}
{{- if and .Values.gatewayKey.value (not .Values.gatewayKey.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "air-gateway.fullname" . }}-key
  labels:
    {{- include "air-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  GATEWAY_KEY: {{ .Values.gatewayKey.value | quote }}
{{- end }}
